# -*- coding: utf-8 -*-
"""WeatherAPIautomation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8K4xkH9ZMAZJH85ZtAlKb60U0NpRy8o
"""

# Make a HTTP request
import requests

#import Date&Time
import datetime

import os
# importing necessary functions from dotenv library
from dotenv import load_dotenv, dotenv_values 
# loading variables from .env file
load_dotenv() 



#api Key
APIKEY=os.getenv("key") #Get your api KEY from "open weather api" portal

#url
BaseURL='http://api.openweathermap.org/data/2.5/weather'

Greetings='Welcome to our  weather reporter! Select a city to view?'
print(Greetings)

#enter city
City=input("Enter a City Name: ")
RequestURL=f'{BaseURL}?appid={APIKEY}&q={City}'
Response=requests.get(RequestURL)

#if response is 'ok' then get the whole JSON weather data as a python dictionary
if Response.status_code==200:
  Data=Response.json()
  print(Data)
else:
  print("Something went wrong, try again !")

#View specific data,

Greetings='Welcome to our  weather reporter! Select a city to view?'
print(Greetings)

#enter city
City=input("Enter a City Name: ")
RequestURL=f'{BaseURL}?appid={APIKEY}&q={City}'
Response=requests.get(RequestURL)

#if response is 'ok' then get the whole JSON weather data as a python dictionary
if Response.status_code==200:
  Data=Response.json()
  weather=Data['weather'][0]['description']
  temperature=round(Data['main']['temp']-273.15,2)
  sunrise=datetime.datetime.utcfromtimestamp(Data['sys']['sunrise']+Data['timezone'])
  sunset=datetime.datetime.utcfromtimestamp(Data['sys']['sunset']+Data['timezone'])

  print('Weather Summary: ',weather)
  print('Temperature is: ', temperature,'Celsius')
  print('Sunrise at: ', sunrise)
  print('Sunset at: ', sunset)
else:
  print("Something went wrong, tryagain !")
